name: pegon_ai_mobile
description: "pegon script transliteration app"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_storage: ^2.1.1
  google_sign_in: ^6.3.0
  dio: ^5.8.0+1
  cached_network_image: ^3.4.1
  google_mobile_ads: ^5.1.0
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  pinput: ^5.0.1
  image_picker: ^1.1.2
  carousel_slider: ^5.0.0
  youtube_player_iframe: ^5.2.1
  webview_flutter: ^4.13.0
  ultralytics_yolo: ^0.1.14
  camera: ^0.11.1
  loader_overlay: ^5.0.0
  device_info_plus: ^11.4.0
  flutter_native_splash: ^2.4.6
  double_back_to_close_app: ^2.1.0
  midtrans_snap: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.webp"
  min_sdk_android: 21
  background_color: "#FF990E"

flutter_native_splash:
  image: "assets/images/logo.png"
  color: "#FF990E"
  android_12:
    image: "assets/images/logo.png"
    color: "#FF990E"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.webp
    - assets/images/login.webp
    - assets/images/register.webp
    - assets/images/otp.webp
    - assets/images/upgrade.webp
    - assets/images/google.webp
    - assets/images/avatar_boy.webp
    - assets/images/avatar_girl.webp
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
        - asset: assets/fonts/Nunito-BlackItalic.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito-BoldItalic.ttf
        - asset: assets/fonts/Nunito-ExtraBold.ttf
        - asset: assets/fonts/Nunito-ExtraBoldItalic.ttf
        - asset: assets/fonts/Nunito-ExtraLight.ttf
        - asset: assets/fonts/Nunito-ExtraLightItalic.ttf
        - asset: assets/fonts/Nunito-Italic.ttf
        - asset: assets/fonts/Nunito-Light.ttf
        - asset: assets/fonts/Nunito-LightItalic.ttf
        - asset: assets/fonts/Nunito-Medium.ttf
        - asset: assets/fonts/Nunito-MediumItalic.ttf
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
        - asset: assets/fonts/Nunito-SemiBoldItalic.ttf
